//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int IdRegistro { get; set; }
        public Nullable<int> IdItem { get; set; }
        public Nullable<decimal> Nivel { get; set; }
        public Nullable<int> Odometro { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public Nullable<decimal> Presion { get; set; }
        public Nullable<bool> BotonPanico { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
